### PR TITLE
Remove transaction count related docs

### PR DESCRIPTION
**Pull request by chanikag**
$subject as the management API for transaction count is removed

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by SanojPunchihewa** [comment]
Shall we remove the CLI docs as well? https://mi.docs.wso2.com/en/latest/observe-and-manage/managing-integrations-with-micli/#monitor-transactions

**Comment by chanikag** [comment]
> Shall we remove the CLI docs as well? https://mi.docs.wso2.com/en/latest/observe-and-manage/managing-integrations-with-micli/#monitor-transactions

Yes doing in https://github.com/wso2/docs-mi/pull/926/files#diff-2a323dfb5f157a1edfdac063b6e453993ca42dfc3211b10f8f79716ed9c88366

**Comment by SanojPunchihewa** [comment]
Do we need update or remove this page http://localhost:8000/en/latest/install-and-setup/setup/deployment-best-practices/monitoring-transaction-counts/ ?

**Comment by chanikag** [comment]
> [install-and-setup/setup/deployment-best-practices/monitoring-transaction-counts/](http://localhost:8000/en/latest/install-and-setup/setup/deployment-best-practices/monitoring-transaction-counts/) ?

Yes, this has to be removed. https://github.com/wso2/docs-mi/pull/926/commits/e84a603c147d1d34fcc9b05aa254736353e59dc7 removed from mkdocs.yml

**Review by DinithiDiaz — APPROVED** [review]

**Comment by SanojPunchihewa** [comment]
We have references for the `Monitoring Integration Transactions Counts ` page in DB setup pages. eg https://mi.docs.wso2.com/en/latest/install-and-setup/setup/databases/setting-up-mysql/. If we remove the page from mkdocs. yml will they get redirected?

**Comment by chanikag** [comment]
> We have references for the `Monitoring Integration Transactions Counts ` page in DB setup pages. eg https://mi.docs.wso2.com/en/latest/install-and-setup/setup/databases/setting-up-mysql/. If we remove the page from mkdocs. yml will they get redirected?

This is done

**Review by SanojPunchihewa — APPROVED** [review]

**Pull request merged**
