### PR TITLE
[4.3.0] Update email-connector-config.md

### PR DESCRIPTION
**Pull request by DinithiDiaz**
## Purpose
$subject

Fixes https://github.com/wso2/docs-mi/issues/65.

### CODE REVIEW

**Comment by DinithiDiaz** [comment]
Updated UI:
email-4 3

**Comment by chanikag** [comment]
This note should come inside send operation

**Comment by chanikag** [comment]
Can you add a screenshot of the doc

**Comment by DinithiDiaz** [comment]
Updated UI:

https://github.com/user-attachments/assets/fb541a85-1340-4ead-802b-cd17d36e9c0c

**Comment by DinithiDiaz** [comment]
Update UI:


https://github.com/user-attachments/assets/41a237d9-0008-4816-b70b-c84211ff64d5

**Review by chanikag — APPROVED** [review]

**Pull request merged**
